version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt-get update
      - apt install hugo nodejs -y
      - npm install postcss -g
      - cd default && npm install
  build:
    commands:
      - cd default
      - hugo
      - aws s3 sync public/ s3://brcloudsolutions.com/ --delete
      - aws s3 sync public/ s3://brcloudsolutions.com.br/ --delete
