version: 0.2
env:
  variables:
    HUGO_VERSION: 0.121.1
phases:
  install:
    commands:
      - mkdir -p /tmp/codebuild/bin
      - wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_$HUGO_VERSION_linux-arm64.tar.gz -q -o /dev/null
      - tar -xf hugo_$HUGO_VERSION_linux-arm64.tar.gz
      - cp hugo /tmp/codebuild/bin/hugo
      - npm install postcss -g
      - npm install
  build:
    commands:
      - ls -ltha /tmp/codebuild/bin
      - cd default
      - hugo
      - aws s3 sync public/ s3://brcloudsolutions.com/ --delete
      - aws s3 sync public/ s3://brcloudsolutions.com.br/ --delete
