version: 0.2
phases:
  install:
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v0.121.2/hugo_0.121.2_linux-arm64.tar.gz -q -o /dev/null
      - tar -xf hugo_0.121.2_linux-arm64.tar.gz
      - mkdir -p /tmp/codebuild/bin
      - mv hugo /tmp/codebuild/bin/hugo
  build:
    commands:
      - hugo
