name = "Docsy"
license = "Apache 2.0"
licenselink = "https://github.com/google/docsy/blob/main/LICENSE"
description = "A Hugo theme for technical documentation sites"
homepage = "http://localhost:8080"
tags = ["documentation", "multilingual", "customizable", "responsive", "docs"]
features = []
min_version = "0.110.0"

[author]
  name = "The Docsy Authors"
  homepage = "http://localhost:8080"
